default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: administrator
  password: '!Pillar10#'

development:
  <<: *default
  database: spaghetti-boil_development

test:
  <<: *default
  database: spaghetti-boil_test
